server:
  port: 8892

debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    io.github.gdtknight: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fastcampus
    username: fastcampus
    password: fast1234
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true # sql_formatting
      hibernate.default_batch_fetch_size: 100 # bulk query
  h2.console.enabled: false
  sql.init.mode: always
  # thymeleaf.cache: false
  # data.rest:
  #   base-path: /api
  #   detection-strategy: annotated

---

spring:
  config.activate.on-profile: testdb
  # datasource:
  #   url: jdbc:h2:mem:board;mode=mysql
  #   driverClassName: org.h2.Driver
  # sql.init.mode: always
  # test.database.replace: none
