server:
  port: 8892

debug: false
management.endpoints.web.exposure.include: "*"
logging:
  level:
    io.github.gdtknight: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  thymeleaf3:
    decoupled-logic: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fastcampus
    username: fastcampus
    password: fast1234
    # url: jdbc:h2:mem:testdb
    # username: sa
    # driver-class-name: org.h2.Driver
    # h2:
    #   console:
    #     enabled: true
    #     settings:
    #       web-allow-others: true
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true # sql_formatting
      hibernate.default_batch_fetch_size: 100 # bulk query
  sql.init.mode: always
  # thymeleaf.cache: false
  data.rest:
    base-path: /api
    detection-strategy: annotated

---

spring:
  config.activate.on-profile: testdb # H2를 통해서 다양한 데이터베이스 시뮬레이션이 가능
  datasource:
    url: jdbc:h2:mem:board;mode=mariadb
    driverClassName: org.h2.Driver
  sql.init.mode: always
  test.database.replace: none  # 모든 테스트는 상단의 프로필을 사용하여 수행하겠다는 옵션
